### ISSUE TITLE
something looks wrong in MMOE.py (pytorch version)

### ISSUE THREAD

**Issue by XuweiC** [QunBB/DeepLearning#2]
result of the main（I only changed the size of the input）
I create the test data of (4,8), the output was the same,

task_output tensor([[-0.0373, -0.0265],
        [-0.0373, -0.0265],
        [-0.0373, -0.0265],
        [-0.0373, -0.0265]], grad_fn=<MmBackward>)
task_output tensor([[-0.0157,  0.0096],
        [-0.0157,  0.0096],
        [-0.0157,  0.0096],
        [-0.0157,  0.0096]], grad_fn=<MmBackward>)
OrderedDict([('click', tensor([[0.4973, 0.5027],
        [0.4973, 0.5027],
        [0.4973, 0.5027],
        [0.4973, 0.5027]], grad_fn=<SoftmaxBackward>)), ('like', tensor([[0.4937, 0.5063],
        [0.4937, 0.5063],
        [0.4937, 0.5063],
        [0.4937, 0.5063]], grad_fn=<SoftmaxBackward>))])
click torch.Size([4, 2])
like torch.Size([4, 2])

Can you help me figure out this? Thanks

**Comment by QunBB** [comment]
I used the `normal_` initialization in `DNN`(i think it is probably a not good initialization). 
Now i change to use the `kaiming_normal_`.
You could see the latest code that i has commited. [utils.py(DNN-\_\_init\_\_)](https://github.com/QunBB/DeepLearning/blob/main/multitasklearning/torch/utils.py#L55)
